// GAMEGPS ACCOUNT V6.6.1 — Auth + player cloud saves
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const db=createClient('https://afyavcczswxoievqyanb.supabase.co','sb_publishable_bqDSr5xHf3y3uU-ULjhruA_cmeUilR5');
const $=id=>document.getElementById(id),status=$('accountStatus'),guest=$('accountGuest'),connected=$('accountConnected');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const show=msg=>{status.textContent=msg};
function saveQuery(s){const targets=Array.isArray(s.data?.targets)?s.data.targets:[];return targets.length?targets.join(' + '):(s.title||'')}
function progress(s){const done=Array.isArray(s.data?.done)?s.data.done.length:0,total=Number(s.data?.total||0);return {done,total,percent:total?Math.round(done/total*100):null}}
async function loadSaves(){const box=$('accountSaves');if(!box)return;box.innerHTML='<div class="wf-status">Chargement de tes sauvegardes...</div>';const {data,error}=await db.from('game_saves').select('game_id,save_key,title,data,updated_at').order('updated_at',{ascending:false});if(error){box.innerHTML=`<div class="wf-status">Impossible de charger les sauvegardes : ${esc(error.message)}</div>`;return}if(!data?.length){box.innerHTML='<div class="wf-status">Aucun parcours sauvegardé pour le moment. Lance un Assistant GPS Warframe pour créer ta première sauvegarde.</div>';return}box.innerHTML=data.map(s=>{const p=progress(s),q=saveQuery(s),label=s.title||q||'Parcours GameGPS',info=p.total?`${p.done}/${p.total} besoins • ${p.percent}%`:`${p.done} besoins obtenus`,href=s.game_id==='warframe'?`warframe.html?assistant=${encodeURIComponent(q)}#warframeSearchResults`:'#';return `<article class="account-save-card"><span class="wf-kicker">${esc(String(s.game_id||'GAME').toUpperCase())}</span><h3>${esc(label)}</h3><p>${esc(info)}</p><small>Dernière synchro : ${esc(new Date(s.updated_at).toLocaleString('fr-FR'))}</small>${q?`<a class="button" href="${href}">REPRENDRE LE PARCOURS</a>`:''}</article>`}).join('')}
async function render(session){const u=session?.user;guest.hidden=!!u;connected.hidden=!u;if(u){$('accountPlayerName').textContent=u.user_metadata?.username||u.user_metadata?.full_name||'JOUEUR GAMEGPS';$('accountEmail').textContent=u.email||'Compte Discord';show('Compte connecté • synchronisation cloud active.');await loadSaves()}else show('Connecte-toi ou crée ton GameGPS ID pour synchroniser ta progression.')}
$('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();show('Connexion...');const {error}=await db.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)return show('Connexion impossible : '+error.message);const {data}=await db.auth.getSession();await render(data.session)});
$('signupForm')?.addEventListener('submit',async e=>{e.preventDefault();show('Création du compte...');const {data,error}=await db.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{username:$('signupName').value.trim()},emailRedirectTo:location.href.split('#')[0]}});if(error)return show('Création impossible : '+error.message);if(data.session)await render(data.session);else show('Compte créé. Vérifie ton email pour confirmer ton GameGPS ID.')});
$('discordLogin')?.addEventListener('click',()=>show('Discord sera activé dès que les identifiants OAuth GameGPS auront été configurés.'));
$('logoutButton')?.addEventListener('click',async()=>{await db.auth.signOut();await render(null)});
db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>render(session),0)});
const {data}=await db.auth.getSession();await render(data.session);
window.GameGPSAuth={client:db,getSession:()=>db.auth.getSession()};