// GAMEGPS — WARFRAME RELICS MODULE V5.7
// Relic GPS: direct relic search, rewards, rarity and acquisition sources.
(()=>{
const W=()=>window.WarframeGPS;
const norm=s=>W()?.normalize(s)||String(s||"").toLowerCase();
const isRelic=item=>{const n=norm(item?.name),c=norm(item?.category||item?.type||item?.productCategory);return n.includes("relic")||c.includes("relic")||/^(lith|meso|neo|axi)\s+[a-z0-9]+/i.test(item?.name||"")};
const rarity=r=>r?.rarity||r?.tier||r?.reward?.rarity||"Rareté non précisée";
const chance=r=>{const w=W(),v=r?.chance??r?.dropChance??r?.probability;return v!=null?w.formatChance({chance:v}):"Taux selon raffinement"};
function rewards(item){const arr=[];for(const key of ["rewards","drops","relicRewards"]){if(Array.isArray(item?.[key]))item[key].forEach(x=>arr.push(x))}return arr}
function rewardName(r){return r?.item||r?.name||r?.reward?.name||r?.rewardName||"Récompense"}
function sources(item){const w=W(),drops=w.getDrops(item);return drops.slice(0,8)}
function tier(name){const m=String(name||"").match(/^(Lith|Meso|Neo|Axi)/i);return m?m[1]:"Relique"}
function fissureHint(name){const t=tier(name).toLowerCase(),h={lith:"Lance une Fissure Lith active.",meso:"Lance une Fissure Meso active.",neo:"Lance une Fissure Neo active.",axi:"Lance une Fissure Axi active."};return h[t]||"Lance une Fissure du même palier que la relique."}
function render(item){const w=W(),name=item?.name||"Relique",rw=rewards(item),src=sources(item),image=item?.imageName?`https://cdn.warframestat.us/img/${item.imageName}`:"";w.results.innerHTML=`<article class="wf-result-card"><div class="wf-result-head">${image?`<img src="${image}" alt="${w.escape(name)}">`:""}<div><span class="wf-kicker">GAMEGPS / RELIQUE V5.7</span><h3>${w.escape(name)}</h3><small>${w.escape(tier(name).toUpperCase())} RELIC</small></div></div><p class="wf-description">${w.escape(item?.description||"Relique du Néant contenant des récompenses Prime.")}</p><div class="wf-route"><div><span>GPS RELIQUE</span><strong>${w.escape(fissureHint(name))}</strong><small>Équipe la relique avant la mission, collecte 10 Réactifs puis choisis une récompense à l'extraction.</small></div></div>${rw.length?`<div class="wf-components"><h4>CONTENU DE LA RELIQUE</h4>${rw.slice(0,12).map(r=>`<div class="wf-row"><span><b>${w.escape(rewardName(r))}</b><small>${w.escape(rarity(r))}</small></span><strong>${w.escape(chance(r))}</strong></div>`).join("")}</div>`:"<div class="wf-status">Le contenu détaillé de cette relique n'est pas fourni par cette fiche API.</div>"}${src.length?`<div class="wf-components"><h4>OÙ OBTENIR LA RELIQUE</h4>${src.map(d=>`<div class="wf-row"><span><b>${w.escape(w.routePath(d))}</b><small>Source détectée</small></span><strong>${w.escape(w.formatChance(d))}</strong></div>`).join("")}</div>`:""}</article>`}
async function searchRelic(item){render(item)}
function install(){const w=W();if(!w||w._relics57)return;w._relics57=true;const previous=w.search.bind(w);w.search=async function(){const q0=this.input.value.trim();if(!q0)return this.message("Entre le nom d'une ressource, Warframe, arme ou relique.");this.results.innerHTML=`<div class="wf-status">Construction du GPS complet pour <strong>${this.escape(q0)}</strong>...</div>`;try{const items=this.normalizeResults(await this.fetchJSON(`${WARFRAME_API}/items/search/${encodeURIComponent(q0)}`));if(!items.length)return this.message(`Aucun résultat pour « ${q0} ».`);const q=this.normalize(q0),exact=items.find(i=>this.normalize(i.name)===q)||items[0];if(isRelic(exact)){this.currentItem=exact;this.components=[];return searchRelic(exact)}return previous()}catch(e){console.error("GameGPS Relics V5.7:",e);return previous()}}}
window.WarframeRelics={isRelic,render};document.addEventListener("DOMContentLoaded",()=>setTimeout(install,1));if(document.readyState!=="loading")setTimeout(install,1);
})();