// GAMEGPS — WARFRAME RELICS MODULE V5.8
// Relic GPS: rewards by refinement + acquisition sources from official-derived drop data.
(()=>{
const W=()=>window.WarframeGPS, DROP_BASE="https://drops.warframestat.us/data";
const norm=s=>W()?.normalize(s)||String(s||"").toLowerCase();
const looks=s=>{const n=norm(s);return n.includes("relic")||n.includes("relique")||/\b(lith|meso|neo|axi)\s+[a-z0-9]+\b/i.test(String(s||""))};
const isRelic=i=>i&&[i.name,i.category,i.type,i.productCategory].some(looks);
function parse(q){const m=String(q||"").match(/\b(Lith|Meso|Neo|Axi)\s+([A-Z0-9]+)\b/i);return m?{tier:m[1][0].toUpperCase()+m[1].slice(1).toLowerCase(),code:m[2].toUpperCase()}:null}
const esc=s=>W().escape(String(s??""));
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status}`);return r.json()}
async function relicData(p){if(!p)return null;try{return await json(`${DROP_BASE}/relics/${encodeURIComponent(p.tier)}/${encodeURIComponent(p.code)}.json`)}catch(e){return null}}
function states(data){if(!data)return{};if(data.rewards&&!Array.isArray(data.rewards))return data.rewards;if(Array.isArray(data.rewards))return {[data.state||"Intact"]:data.rewards};return{}}
function chance(v){const n=Number(v);return Number.isFinite(n)?`${n}%`:"—"}
function rarityClass(r){const n=norm(r);return n.includes("rare")&&!n.includes("uncommon")?"RARE":n.includes("uncommon")?"PEU COMMUN":"COMMUN"}
async function sources(p){if(!p)return[];try{const all=await json(`${DROP_BASE}/missionRewards.json`),needle=`${p.tier} ${p.code} Relic`.toLowerCase(),out=[];for(const [planet,nodes] of Object.entries(all||{})){for(const [node,data] of Object.entries(nodes||{})){for(const [rotation,list] of Object.entries(data?.rewards||{})){for(const r of list||[]){if(String(r?.itemName||"").toLowerCase()===needle)out.push({planet,node,mode:data?.gameMode||"Mission",rotation,chance:r?.chance})}}}}return out.sort((a,b)=>(Number(b.chance)||0)-(Number(a.chance)||0)).slice(0,8)}catch(e){return[]}}
function apiRewards(item){const a=[];for(const k of ["relicRewards","rewards","drops"])if(Array.isArray(item?.[k]))item[k].forEach(x=>a.push({itemName:x?.itemName||x?.rewardName||x?.item||x?.name||x?.reward?.name||"Récompense",rarity:x?.rarity||x?.tier||x?.reward?.rarity||"",chance:x?.chance??x?.dropChance??x?.probability}));return a}
function rewardsHTML(data,item){const w=W(),ss=states(data),order=["Intact","Exceptional","Flawless","Radiant"],keys=order.filter(k=>ss[k]).concat(Object.keys(ss).filter(k=>!order.includes(k)));if(keys.length)return `<div class="wf-components"><h4>CONTENU + RAFFINEMENT</h4>${keys.map((k,idx)=>`<div class="wf-relic-state" style="margin-top:${idx?"14":"0"}px"><div class="wf-row"><span><b>${esc(k.toUpperCase())}</b><small>${k==="Intact"?"Sans raffinage":k==="Radiant"?"Raffinement maximal":"Relique raffinée"}</small></span></div>${(ss[k]||[]).map(r=>`<div class="wf-row"><span><b>${esc(r.itemName||r.rewardName||r.name||"Récompense")}</b><small>${esc(rarityClass(r.rarity))}</small></span><strong>${esc(chance(r.chance))}</strong></div>`).join("")}</div>`).join("")}</div>`;const a=apiRewards(item);return a.length?`<div class="wf-components"><h4>CONTENU DE LA RELIQUE</h4>${a.map(r=>`<div class="wf-row"><span><b>${esc(r.itemName)}</b><small>${esc(rarityClass(r.rarity))}</small></span><strong>${esc(r.chance==null?"Taux selon raffinement":chance(r.chance))}</strong></div>`).join("")}</div>`:`<div class="wf-status">Contenu détaillé indisponible pour cette relique.</div>`}
function sourcesHTML(src){return src.length?`<div class="wf-components"><h4>OÙ FARMER LA RELIQUE</h4>${src.map((s,i)=>`<div class="wf-row"><span><b>${i===0?"★ ":""}${esc(s.planet)} → ${esc(s.node)} → ${esc(s.mode)}</b><small>Rotation ${esc(s.rotation)}${i===0?" • Meilleur taux détecté":""}</small></span><strong>${esc(chance(s.chance))}</strong></div>`).join("")}</div>`:`<div class="wf-status">Aucune source de mission détectée dans les tables actuelles (relique possiblement vaulted ou source spéciale).</div>`}
async function render(item,p){const w=W(),name=item?.name||`${p?.tier||""} ${p?.code||""}`,img=item?.imageName?`https://cdn.warframestat.us/img/${item.imageName}`:"",[data,src]=await Promise.all([relicData(p),sources(p)]),era=p?.tier||"Relique";w.results.innerHTML=`<article class="wf-result-card"><div class="wf-result-head">${img?`<img src="${img}" alt="${esc(name)}">`:""}<div><span class="wf-kicker">GAMEGPS / RELIQUE V5.8</span><h3>${esc(name)}</h3><small>${esc(era.toUpperCase())} RELIC</small></div></div><p class="wf-description">${esc(item?.description||"Relique du Néant contenant des récompenses Prime.")}</p><div class="wf-route"><div><span>GPS RELIQUE</span><strong>${src[0]?`${esc(src[0].planet)} → ${esc(src[0].node)} → ${esc(src[0].mode)}`:`Lance une Fissure ${esc(era)} active.`}</strong><small>${src[0]?`Farm recommandé • Rotation ${esc(src[0].rotation)} • ${esc(chance(src[0].chance))}`:"Équipe la relique, collecte 10 Réactifs puis ouvre-la à l'extraction."}</small></div></div>${rewardsHTML(data,item)}${sourcesHTML(src)}</article>`}
async function find(q){const w=W();for(const s of [q,`Relique ${q}`,`${q} Relic`]){try{const a=w.normalizeResults(await w.fetchJSON(`${WARFRAME_API}/items/search/${encodeURIComponent(s)}`)),hit=a.find(isRelic);if(hit)return hit}catch(e){}}return null}
async function run(){const w=W(),input=document.getElementById("warframeSearchInput");if(!w||!input||!looks(input.value))return false;const q=input.value.trim(),p=parse(q);w.results.innerHTML=`<div class="wf-status">Construction du GPS relique pour <strong>${esc(q)}</strong>...</div>`;const item=await find(q);if(!item)return w.message(`Aucune relique trouvée pour « ${q} ».`);w.currentItem=item;w.components=[];await render(item,p||parse(item.name));return true}
function install(){const btn=document.getElementById("warframeSearchButton"),input=document.getElementById("warframeSearchInput");if(!btn||!input||btn.dataset.relic58)return false;btn.dataset.relic58="1";btn.addEventListener("click",async e=>{if(looks(input.value)){e.stopImmediatePropagation();e.preventDefault();await run()}},true);input.addEventListener("keydown",async e=>{if(e.key==="Enter"&&looks(input.value)){e.stopImmediatePropagation();e.preventDefault();await run()}},true);return true}
window.WarframeRelics={isRelic,render,run};let n=0,t=setInterval(()=>{if(install()||++n>40)clearInterval(t)},50);
})();