// GAMEGPS — WARFRAME RELICS MODULE V5.11
// Relic GPS: direct drop-table rendering + resilient item lookup.
(()=>{
const W=()=>window.WarframeGPS, DROP_BASE="https://drops.warframestat.us/data", WFCD_RELICS="https://unpkg.com/warframe-items@latest/data/json/Relics.json";
const cache={json:new Map(),items:new Map(),relics:new Map(),sources:new Map()};
const norm=s=>W()?.normalize(s)||String(s||"").toLowerCase();
const looks=s=>{const n=norm(s);return n.includes("relic")||n.includes("relique")||/\b(lith|meso|neo|axi)\s+[a-z0-9]+\b/i.test(String(s||""))};
const isRelic=i=>i&&[i.name,i.category,i.type,i.productCategory].some(looks);
function parse(q){const m=String(q||"").match(/\b(Lith|Meso|Neo|Axi)\s+([A-Z0-9]+)\b/i);return m?{tier:m[1][0].toUpperCase()+m[1].slice(1).toLowerCase(),code:m[2].toUpperCase()}:null}
const key=p=>p?`${p.tier}:${p.code}`:"",esc=s=>W().escape(String(s??""));
async function json(url){if(cache.json.has(url))return cache.json.get(url);const promise=fetch(url).then(r=>{if(!r.ok)throw new Error(`${r.status}`);return r.json()}).catch(e=>{cache.json.delete(url);throw e});cache.json.set(url,promise);return promise}
async function relicData(p){const k=key(p);if(!k)return null;if(cache.relics.has(k))return cache.relics.get(k);const promise=json(`${DROP_BASE}/relics/${encodeURIComponent(p.tier)}/${encodeURIComponent(p.code)}.json`).catch(()=>null);cache.relics.set(k,promise);return promise}
function states(data){if(!data)return{};if(data.rewards&&!Array.isArray(data.rewards))return data.rewards;if(Array.isArray(data.rewards))return {[data.state||"Intact"]:data.rewards};return{}}
function chance(v){const n=Number(v);return Number.isFinite(n)?`${n}%`:"—"}
function rarityClass(r){const n=norm(r);return n.includes("rare")&&!n.includes("uncommon")?"RARE":n.includes("uncommon")?"PEU COMMUN":"COMMUN"}
async function sources(p){const k=key(p);if(!k)return[];if(cache.sources.has(k))return cache.sources.get(k);const promise=(async()=>{try{const all=await json(`${DROP_BASE}/missionRewards.json`),needle=`${p.tier} ${p.code} Relic`.toLowerCase(),out=[];for(const [planet,nodes] of Object.entries(all||{}))for(const [node,data] of Object.entries(nodes||{}))for(const [rotation,list] of Object.entries(data?.rewards||{}))for(const r of list||[])if(String(r?.itemName||"").toLowerCase()===needle)out.push({planet,node,mode:data?.gameMode||"Mission",rotation,chance:r?.chance});return out.sort((a,b)=>(Number(b.chance)||0)-(Number(a.chance)||0)).slice(0,6)}catch(e){return[]}})();cache.sources.set(k,promise);return promise}
function apiRewards(item){const a=[];for(const k of ["relicRewards","rewards","drops"])if(Array.isArray(item?.[k]))item[k].forEach(x=>a.push({itemName:x?.itemName||x?.rewardName||x?.item||x?.name||x?.reward?.name||"Récompense",rarity:x?.rarity||x?.tier||x?.reward?.rarity||"",chance:x?.chance??x?.dropChance??x?.probability}));return a}
function rewardRows(list){return (list||[]).map(r=>`<div class="wf-row"><span><b>${esc(r.itemName||r.rewardName||r.name||"Récompense")}</b><small>${esc(rarityClass(r.rarity))}</small></span><strong>${esc(chance(r.chance))}</strong></div>`).join("")}
function rewardsHTML(data,item){const ss=states(data),order=["Intact","Exceptional","Flawless","Radiant"],keys=order.filter(k=>ss[k]).concat(Object.keys(ss).filter(k=>!order.includes(k)));if(keys.length){const first=keys[0];return `<div class="wf-components"><h4>CONTENU + RAFFINEMENT</h4><div class="wf-relic-tabs" style="display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px">${keys.map(k=>`<button type="button" data-relic-tab="${esc(k)}" style="padding:10px 14px;border:1px solid #24435a;background:${k===first?"#5fd9f3":"#0b1722"};color:${k===first?"#07111a":"#d9e7f3"};font-weight:800;cursor:pointer">${esc(k.toUpperCase())}</button>`).join("")}</div>${keys.map(k=>`<div data-relic-panel="${esc(k)}" style="display:${k===first?"block":"none"}">${rewardRows(ss[k])}</div>`).join("")}</div>`}const a=apiRewards(item);return a.length?`<div class="wf-components"><h4>CONTENU DE LA RELIQUE</h4>${rewardRows(a)}</div>`:`<div class="wf-status">Contenu détaillé indisponible pour cette relique.</div>`}
function sourcesHTML(src){return src.length?`<div class="wf-components"><h4>MEILLEURES MISSIONS POUR FARMER LA RELIQUE</h4>${src.map((s,i)=>`<div class="wf-row"><span><b>${i===0?"★ ":""}${esc(s.planet)} → ${esc(s.node)} → ${esc(s.mode)}</b><small>Rotation ${esc(s.rotation)}${i===0?" • Recommandé":""}</small></span><strong>${esc(chance(s.chance))}</strong></div>`).join("")}</div>`:`<div class="wf-status">Aucune source de mission détectée dans les tables actuelles (relique possiblement vaulted ou source spéciale).</div>`}
function bindTabs(){const root=W().results;root.querySelectorAll("[data-relic-tab]").forEach(btn=>btn.addEventListener("click",()=>{const k=btn.dataset.relicTab;root.querySelectorAll("[data-relic-panel]").forEach(p=>p.style.display=p.dataset.relicPanel===k?"block":"none");root.querySelectorAll("[data-relic-tab]").forEach(b=>{const on=b.dataset.relicTab===k;b.style.background=on?"#5fd9f3":"#0b1722";b.style.color=on?"#07111a":"#d9e7f3"})}))}
function shell(item,p,data){const w=W(),name=item?.name||`${p?.tier||""} ${p?.code||""} Relic`,img=item?.imageName?`https://cdn.warframestat.us/img/${item.imageName}`:"",era=p?.tier||"Relique";w.results.innerHTML=`<article class="wf-result-card"><div class="wf-result-head">${img?`<img src="${img}" alt="${esc(name)}">`:""}<div><span class="wf-kicker">GAMEGPS / RELIQUE V5.11</span><h3>${esc(name)}</h3><small>${esc(era.toUpperCase())} RELIC</small></div></div><p class="wf-description">${esc(item?.description||"Relique du Néant contenant des récompenses Prime.")}</p><div class="wf-route" id="relicRoute"><div><span>GPS RELIQUE</span><strong>Lance une Fissure ${esc(era)} active.</strong><small>Recherche des meilleures missions de farm en arrière-plan…</small></div></div>${rewardsHTML(data,item)}<div id="relicSources"><div class="wf-status">Chargement des routes de farm…</div></div></article>`;bindTabs()}
async function render(item,p){const data=await relicData(p);shell(item,p,data);const src=await sources(p),route=document.getElementById("relicRoute"),box=document.getElementById("relicSources");if(route&&src[0])route.innerHTML=`<div><span>GPS RELIQUE</span><strong>${esc(src[0].planet)} → ${esc(src[0].node)} → ${esc(src[0].mode)}</strong><small>Farm recommandé • Rotation ${esc(src[0].rotation)} • ${esc(chance(src[0].chance))}</small></div>`;if(box)box.innerHTML=sourcesHTML(src)}
async function find(q,p){const k=norm(q);if(cache.items.has(k))return cache.items.get(k);const promise=(async()=>{const w=W();for(const s of [q,String(q).replace(/\s+Relic$/i,''),`${p?.tier||''} ${p?.code||''}`.trim()]){if(!s)continue;try{const a=w.normalizeResults(await w.fetchJSON(`${WARFRAME_API}/items/search/${encodeURIComponent(s)}`));const exact=a.find(x=>parse(x?.name)?.tier===p?.tier&&parse(x?.name)?.code===p?.code),hit=exact||a.find(isRelic);if(hit)return hit}catch(e){}}try{const all=await json(`${WFCD_RELICS}?gamegps=511`),hit=(Array.isArray(all)?all:[]).find(x=>{const xp=parse(x?.name);return xp&&xp.tier===p?.tier&&xp.code===p?.code});if(hit)return {...hit,name:`${p.tier} ${p.code} Relic`}}catch(e){}return p?{name:`${p.tier} ${p.code} Relic`,type:'Relic',category:'Relics'}:null})();cache.items.set(k,promise);return promise}
async function run(){const w=W(),input=document.getElementById("warframeSearchInput");if(!w||!input||!looks(input.value))return false;const q=input.value.trim(),p=parse(q);if(!p)return w.message(`Format de relique non reconnu pour « ${q} ».`);w.results.innerHTML=`<div class="wf-status">Recherche de <strong>${esc(q)}</strong>...</div>`;const item=await find(q,p);w.currentItem=item;w.components=[];await render(item,p);return true}
function install(){const btn=document.getElementById("warframeSearchButton"),input=document.getElementById("warframeSearchInput");if(!btn||!input||btn.dataset.relic511)return false;btn.dataset.relic511="1";btn.addEventListener("click",async e=>{if(looks(input.value)){e.stopImmediatePropagation();e.preventDefault();await run()}},true);input.addEventListener("keydown",async e=>{if(e.key==="Enter"&&looks(input.value)){e.stopImmediatePropagation();e.preventDefault();await run()}},true);return true}
window.WarframeRelics={isRelic,render,run,cache};let n=0,t=setInterval(()=>{if(install()||++n>40)clearInterval(t)},50);
})();