// GAMEGPS — WARFRAME WEAPONS MODULE V5.6
// Adds weapon crafting GPS without changing the validated Warframe/resource engines.
(()=>{
const W=()=>window.WarframeGPS;
const weaponCats=["primary","secondary","melee","arch-gun","arch-melee","weapon"];
const isWeapon=item=>{const w=W();if(!w||!item)return false;const cat=w.normalize(item.category||item.type||item.productCategory);return weaponCats.some(x=>cat.includes(x))&&!cat.includes("warframe")&&!w.isResourceItem(item)};
async function recipeFor(item){const w=W();await w.recipeData();const recipes=w._recipes||{};if(item?.uniqueName){const hit=Object.values(recipes).find(r=>r?.resultType===item.uniqueName);if(hit)return hit}const target=w.compact(item?.name);for(const [key,r] of Object.entries(recipes)){const result=w.compact(String(r?.resultType||"").split("/").pop());if(result===target||w.compact(key)===target)return r}return null}
async function build(item){const w=W(),recipe=await recipeFor(item),rows=[];if(recipe?.ingredients?.length){for(const x of recipe.ingredients){const qty=Number(x.ItemCount)||1,name=w.ingredientName(x.ItemType);if(qty>0)rows.push({name,itemCount:qty,uniqueName:x.ItemType,_primary:false,_forParts:["Fabrication"]})}}
if(!rows.length&&Array.isArray(item.components))item.components.forEach(x=>rows.push({...x,_primary:false,_forParts:["Fabrication"]}));
const enriched=await Promise.all(rows.map(async r=>{const route=w.resourceGuide?.(r.name);if(route)return {...r,_weaponRoute:route};const found=w.normalizeResults(await w.fetchJSON(`${WARFRAME_API}/items/search/${encodeURIComponent(r.name)}`));const exact=found.find(x=>w.normalize(x.name)===w.normalize(r.name));return {...r,_drops:w.getDrops(exact)}}));return enriched}
function source(item){const w=W(),drops=w.getDrops(item);if(drops.length){const d=w.bestDrop(drops);return {path:w.routePath(d),detail:w.formatChance(d)}}const market=String(item?.marketCost||item?.credits||"");return {path:"Schéma / acquisition de l'arme",detail:market?`Coût indiqué : ${market} crédits`:"Source du schéma à confirmer selon l'arme."}}
function key(item,c){const w=W();return `weapon:${w.normalize(item.name)}:${w.normalize(c.name)}`}
function owned(item,c){const w=W(),state=window.GameGPS?.getProgress?.()?.[`weapon:${w.normalize(item.name)}`]||{};return !!state[key(item,c)]}
function toggle(item,input){const w=W(),p=`weapon:${w.normalize(item.name)}`,state=window.GameGPS?.getProgress?.()?.[p]||{};state[input.dataset.weaponOwned]=input.checked;window.GameGPS?.saveProgress?.(p,state);render(item,window.WarframeWeapons.components)}
function row(item,c){const w=W(),route=c._weaponRoute||w.resourceGuide?.(c.name),drop=w.bestDrop(w.getDrops(c)),loc=route?`${route.path} • ${route.method}`:drop?`${w.routePath(drop)} • ${w.formatChance(drop)}`:"Acquisition à identifier",checked=owned(item,c);return `<label class="wf-row wf-check ${checked?"wf-owned":""}"><span><b>${w.escape(c.name)}</b><small>${w.escape(loc)}</small></span><strong><input type="checkbox" data-weapon-owned="${w.escape(key(item,c))}" ${checked?"checked":""}> x${c.itemCount||1}</strong></label>`}
function render(item,components){const w=W(),name=item.name||"Arme",desc=item.description||"Équipement Warframe.",image=item.imageName?`https://cdn.warframestat.us/img/${item.imageName}`:"",src=source(item),done=components.filter(c=>owned(item,c)).length,total=components.length,pct=total?Math.round(done/total*100):0,next=components.find(c=>!owned(item,c));let nextPath=src.path,nextText="OBTENIR LE SCHÉMA";if(next){const r=next._weaponRoute||w.resourceGuide?.(next.name),d=w.bestDrop(w.getDrops(next));nextPath=r?.path||(d?w.routePath(d):"Acquisition à identifier");nextText=`PROCHAIN OBJECTIF : ${next.name}`}
w.results.innerHTML=`<article class="wf-result-card"><div class="wf-result-head">${image?`<img src="${image}" alt="${w.escape(name)}">`:""}<div><span class="wf-kicker">GAMEGPS / ARME V5.6</span><h3>${w.escape(name)}</h3><small>${w.escape(item.category||item.type||"ARME")}</small></div></div><p class="wf-description">${w.escape(desc)}</p><div class="wf-route"><div><span>GPS DE FABRICATION</span><strong>${w.escape(nextPath)}</strong><small>${w.escape(nextText)}</small></div></div>${total?`<div class="wf-farm-progress"><strong>${done}/${total}</strong><span>${pct}% terminé</span><div><i style="width:${pct}%"></i></div></div><div class="wf-components"><h4>COMPOSANTS + RESSOURCES</h4>${components.map(c=>row(item,c)).join("")}</div>`:`<div class="wf-components"><h4>ACQUISITION</h4><div class="wf-row"><span><b>${w.escape(src.path)}</b><small>${w.escape(src.detail)}</small></span></div></div>`}</article>`}
async function searchWeapon(item){const w=W();window.WarframeWeapons.components=await build(item);render(item,window.WarframeWeapons.components)}
function install(){const w=W();if(!w||w._weapons56)return;w._weapons56=true;const baseSearch=w.search.bind(w);w.search=async function(){const q0=this.input.value.trim();if(!q0)return this.message("Entre le nom d'une ressource, Warframe ou arme.");this.results.innerHTML=`<div class="wf-status">Construction du GPS complet pour <strong>${this.escape(q0)}</strong>...</div>`;try{const items=this.normalizeResults(await this.fetchJSON(`${WARFRAME_API}/items/search/${encodeURIComponent(q0)}`));if(!items.length)return this.message(`Aucun résultat pour « ${q0} ».`);const q=this.normalize(q0),exact=items.find(i=>this.normalize(i.name)===q)||items[0];this.currentItem=exact;if(isWeapon(exact))return searchWeapon(exact);if(this.isResourceItem(exact)){this.components=[];return this.renderResource(exact)}this.components=await this.buildCraftPlan(exact);this.render(exact,this.components)}catch(e){console.error("GameGPS Warframe V5.6:",e);return baseSearch()}};w.results.addEventListener("change",e=>{if(e.target.matches("[data-weapon-owned]"))toggle(w.currentItem,e.target)})}
window.WarframeWeapons={components:[],isWeapon,build,render};document.addEventListener("DOMContentLoaded",()=>setTimeout(install,0));if(document.readyState!=="loading")setTimeout(install,0);
})();